<?php
// +----------------------------------------------------------------------
// | When work is a pleasure, life is a joy!
// +----------------------------------------------------------------------
// | User: ShouKun Liu  |  Email:24147287@qq.com  | Time:2016/12/10 23:56
// +----------------------------------------------------------------------
// | TITLE:基础类
// +----------------------------------------------------------------------

namespace backend\controllers;


use yii\db\ActiveRecord;

use yii\web\Controller;



/**
 * Class BaseController
 * @package backend\controllers
 */
class BaseController extends Controller
{
    public $layout =  '@backend/views/layouts/main';

    /**
     * @var array
     */
    public $param;

    public $pageSize = 20;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //all param name is lower
        $this->param = array_merge($this->request->get(), $this->request->post());
    }

    public function getParam($name=null){
        if($name===null || !isset($this->param[$name])){
            return $this->param;
        }
        return $this->param[$name];
    }

    /**
     * @param $m ActiveRecord
     */
    public function loadRequestDataIntoActiveModel($m){
        $ary = explode('\\', $m->className() );
        $m->setAttributes($this->param[$ary[count($ary) - 1]], false);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    /**
     * 错误提示信息
     *
     * @param string $msgText 错误内容
     * @param string $skipUrl 跳转链接
     * @param string $msgType 提示类型 [success/error/info/warning]
     * @return mixed
     */
    protected function message($msgText, $skipUrl, $msgType = null)
    {
        if (!$msgType || !in_array($msgType, ['success', 'error', 'info', 'warning'])) {
            $msgType = 'success';
        }

        \Yii::$app->getSession()->setFlash($msgType, $msgText);
        return $skipUrl;
    }


}

