<?php
/**
 * Created by PhpStorm.
 * Author: yidashi
 * DateTime: 2017/3/8 17:16
 * Description:
 */

namespace api\modules\v1\controllers;


use api\controllers\BaseController;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;

class NotifyController extends BaseController
{
    public function authOptional()
    {
        return ['*'];
        return parent::authOptional(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return Url::to(['site/index']);
        return new ActiveDataProvider([
            //'query' => Notify::find()->where(['to_uid' => \Yii::$app->user->id]),
            'query' => User::find()->where('1=1'),
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC
                ]
            ]
        ]);
    }
}