<?php
namespace backend\components;

use yii\base\Widget;

/**
 * https://www.yiiframework.com/doc/guide/2.0/zh-cn/structure-widgets
 * Class QiniuWidget
 * @package backend\components
 */
class QiniuWidget extends Widget{

    public $label = '云端文件';
    public $filedName = 'img';//input file 的name名称
    public $isMulti = false;
    public $value = [];//已上传的文件远程路径，一个文件就是一个字符串，多个文件就是字符串数组

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('qiniu',[
            'label' => $this->label,
            'filedName' => $this->filedName,
            'isMulti' => $this->isMulti,
            'value' => $this->value,
        ]);
    }


}
